version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security
    groups:
      production-deps:
        dependency-type: production
        update-types:
          - "patch"
          - "minor"
      development-deps:
        dependency-type: development
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security
